### ISSUE TITLE
idea:  Channel not updating through "on_open" function alteration (in example)

### ISSUE THREAD

**Issue by beastwork** [danpaquin/coinbasepro-python#135]
I'm trying to use this tool to make an events streamer for only the activity in my account.  Is this possible?  I can't seem to sort it out.

I've altered your example with the below code but I'm not getting the desired effects.

`class myWebsocketClient(gdax.WebsocketClient):
   
    def on_open(self):
        self.url = "wss://ws-feed.gdax.com/"
        self.products = ['BTC-USD']
        self.channels = ['user']
        self.message_count = 0
        print("Lets count the messages!")
    def on_message(self, msg):
        self.message_count += 1
        if 'price' in msg and 'type' in msg:
            print ("Message type:", msg["type"],
                   "\t@ {:.3f}".format(float(msg["price"])))`

**Comment by lirenz** [comment]
You need to authenticate in the on_open. Try setting:

        self.auth = auth
        self.api_key = api_key
        self.api_secret = api_secret
        self.api_passphrase = api_passphrase

**Comment by rubberduckdubberruck** [comment]
Hey @beastwork, did you ever get this to work?
