### ISSUE TITLE
invalid signature when using an authenticated websocket channel

### ISSUE THREAD

**Issue by scottbecker** [danpaquin/coinbasepro-python#140]
Hello,

The path needs to be '/users/self/verify' when a channel is present during websocket authentication

Line 65 of this [websocket_client.py](https://github.com/danpaquin/gdax-python/blob/master/gdax/websocket_client.py) should be 

path =  '/users/self/verify' if 'channels' in sub_params else '/users/self'
message = timestamp + 'GET' + path

**Comment by kevinszielinski** [comment]
https://docs.gdax.com/#subscribe

Confirmed need for change of /users/self/ to /users/self/verify, not seeing nuance about channels needing /users/self instead. Looking under Authentication under Subscribe for Websocket.

**Comment by rubberduckdubberruck** [comment]
Hey guys, even after this change, were you able to subscribe the the 'users' channel for any product? I get back one subscription message:

```
Message: {'type': 'subscriptions', 'channels': [{'name': 'user', 'product_ids': ['BTC-USD', 'ETH-USD']}]}
```

But no further updates about my activity on these markets appears. My activity _does_ appear wih the 'full' channel, so this makes me think I failed to authenticate correctly in my subscription request or something.

Thanks!
