### ISSUE TITLE
Creating a new real time order book fails

### ISSUE THREAD

**Issue by wbendick** [danpaquin/coinbasepro-python#141]
Creating a new real time order book fails with this error:

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gdax/order_book.py", line 20, in __init__
    self._client = PublicClient(product_id=product_id)
TypeError: __init__() got an unexpected keyword argument 'product_id'

**Comment by ZZZWENG** [comment]
@wbendick  I had the same error with pip version, which contains this bug. Using the latest repo code works for me.

Related Issue is [#134](https://github.com/danpaquin/gdax-python/issues/134)

**Comment by ErenDursun** [comment]
@wbendick try installing the latest git repo with pip
`pip install git+https://github.com/danpaquin/gdax-python.git`
