### ISSUE TITLE
Websocket Crash on Close

### ISSUE THREAD

**Issue by marc-git** [danpaquin/coinbasepro-python#152]
Anybody else have a python crash using 3.6.3 on MacOS ? I get this everytime I issue WebsocketClient.close()

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by hiemal** [comment]
same here,

**Comment by tmechsner** [comment]
Same here. 
The cause seems to be the WebsocketClient thread that is not closed correctly.
I can avoid the error by doing
```
client.stop = True
client.thread.join()
client.ws.close()
```
instead of
`client.close()`

That `self.thread.join()` should be added to the close method.
