### ISSUE TITLE
mongo_collection doesn't seem to be available

### ISSUE THREAD

**Issue by parabuzzle** [danpaquin/coinbasepro-python#155]
I have a fresh install of anaconda3 and I've done:

```
pip install gdax
pip install pymongo
```

I have a mongodb server running locally and when I try to run your example from the README.md:

```python
wsClient = gdax.WebsocketClient(url="wss://ws-feed.gdax.com", products="BTC-USD", mongo_collection=BTC_collection, should_print=False)
```

I get this error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'mongo_collection'
```

**Comment by mattbernardini** [comment]
it is an issue with the version in pip.  Clone the repository and run the setup.py script and you should be good to go.

**Comment by cornyhorse** [comment]
I ran the setup.py script and it looks like it installed properly but I'm getting same error as OP. Anybody else having that problem?

**Comment by li6el** [comment]
Same error.

**Comment by Babyjack** [comment]
Same error...

**Comment by Babyjack** [comment]
Make sure you're using this implementation, versus the GDAX implementation (from pip uninstall gdax).

**Comment by li6el** [comment]
I will try this. I got the webfeed to mongodb by other means.



Sent via the Samsung Galaxy S®6 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by EdwardBurgin** [comment]
Thanks, can confirm running python setup.py install on the git clone works, the problem is on the pip install version. The mongodb storage from the websocket is now running :-)

**Comment by ntrikich** [comment]
Uninstalled the pip version of gdax and tried pip install git+https://github.com/danpaquin/gdax-python.git and still got the error

**Comment by EdwardBurgin** [comment]
As I remember you don't pip install you run the setup.py file from terminal or cmd. ie 'python setup.py install'

**Comment by ntrikich** [comment]
Went back, ran setup.py install in a new environment and still no success. I have to be missing something.

**Comment by robertdelacruz1551** [comment]
I was having the same issue and I resolved this issue by changing the __init__ file in the project folder. In my project I keep the gdax folder in a directory titled "Connections", so I opened the Connections/gdax/__init__.py file and I changed the imports to this:

from _Connections_.gdax.authenticated_client import AuthenticatedClient
from _Connections_.gdax.public_client import PublicClient
from _Connections_.gdax.websocket_client import WebsocketClient
from _Connections_.gdax.order_book import OrderBook

I don't know if this breaks anything but it's working for me

**Comment by johnmarcampbell** [comment]
Any word on when the pip version will be updated?
