### ISSUE TITLE
Too many websockets in typical usage

### ISSUE THREAD

**Issue by mcardillo55** [danpaquin/coinbasepro-python#159]
I think this project is starting to get to a point where a client program will have many redundant websockets to use all the features available.

Example:
If you want to process incoming trades & have live OrderBooks on 5 different products, you will need 6 open websockets for this. Each websocket is receiving the same data, so gdax-python SHOULD just be filtering the data on one open websocket.

Maybe we can create some sort of websocket singleton that can be used by all classes? or combine the orderbook class (that can hopefully support multiple pairs) as an toggle-able option in the websocket class?

Also worth noting that GDAX claims to rate-limit websocket connections:

> The websocket feed is publicly available, but connections to it are rate-limited to 1 per 4 seconds per IP.

**Comment by lirenz** [comment]
Yes. I've submitted an experimental/v1/alpha+probably buggy L2 orderbook where we use a filtration method:

https://github.com/danpaquin/gdax-python/pull/148/commits/a534088b7cc096ec162687e78e177be9bcab0d03

You basically create 1 web-socket & the orderbook has a process_message method (which filters by message type & product_id). The web-socket can subscribe to any number of products / channels.

I was hoping that this becomes standard. The only problem is whether or not we want to diverge from the gdax-node version (which is not my call).

**Comment by mcardillo55** [comment]
@lirenz Glossing over your PR real quick looks like it's a step in the direction. I'm not sure if the current OrderBook really should inherit from the WebsocketClient. Instead we could just process each message in the on_message() of a single application-wide websocket.

**Comment by mcardillo55** [comment]
I reworked the OrderBook code to no longer inherit from the WebsocketClient. However, my "OrderBookConsole" version throws all incoming websocket message into a Queue (also worth noting, this makes the example code python 2.7 exclusive), and then processes the queue in an infinite loop. I'm going to start using it in my application, but would like some more eyes on it before I submit a PR, since it's a pretty large functionality change.

https://github.com/mcardillo55/gdax-python/commit/e33088bb389a486e52c771fe708b74b6bcfed3af
