### ISSUE TITLE
Buy order issue- insufficient funds even though I have sufficient funds?

### ISSUE THREAD

**Issue by ronenshohat** [danpaquin/coinbasepro-python#160]
Just testing the API on sandbox with the following code: 

```
auth_client_sandbox.buy(price='1000.00', #USD
               size= '2.41', #BTC
               product_id='BTC-USD')
```

I have $2412.24 in my fake account, so I have more than enough to fill this order. When I submit this order manually on the sandbox GDAX site it works, but for some reason I get an error message for 'Insufficient funds'. The weird thing is that if I enter size='2.4' it works and enters an order.

I don't really understand how this issue can be caused- anyone experiencing anything similar? Thanks for reading

**Comment by acontry** [comment]
I have encountered this error in the sandbox occasionally also. If I remembered right it happened when there were no resting orders on the book to trade against.

**Comment by ronenshohat** [comment]
No resting orders to trade against? Like if the order book was empty? That's pretty weird- why is the sandbox interface so bad? No real time data, price of BTC doesn't make sense. How are you supposed to test anything on this? Any advice? Thanks

**Comment by acontry** [comment]
Seems like it only works if enough people actually place orders on it, which doesn't seem to be the case. I wrote the tests for this package which rely on the sandbox and only verify basic functionality. For more realistic testing I've used the live exchange - either placing orders deep in the book so I know they won't execute before I cancel them or just by working in the smallest value increments possible to minimize cost.

**Comment by tonightilive** [comment]
You need to add the fee into your calculations and reserve enough USD in your wallet to cover it. In the example order, 1000 * 2.41 = 2410, the fee would be 0.25% of 2410 or 6.025, making the total order cost 2416.025, well over your amount of 2412.24.

Your second example (one that works) is 2.4* 1000 = 2400,  2400*1.0025=2406 which is less than your wallet total.

**Comment by nwalmethule** [comment]
I had decreased the size until 50% of the original, but size parameter doesn't works.
I will try with the funds parameter, it works with json but I don't know with the this program.
I will say.
