### ISSUE TITLE
issue with importing classes from gdax

### ISSUE THREAD

**Issue by Prajit65** [danpaquin/coinbasepro-python#163]
Hi, whenever i try to use the classes in gdax folder (after installing gdax for python) i get the following error
~$ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdax
>>> auth_client = gdax.AuthenticatedClient(api_key, api_secret, api_passphrase, api_url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'AuthenticatedClient'

This happens if try to import PublicClient, WebSocketClient etc
Tried upgrading pip, even reinstalled ubuntu (my version is 16.04) but it still wont work and shows the same error

**Comment by bpross** [comment]
It works for me. How I got it to work:
```
git clone https://github.com/danpaquin/gdax-python.git
activate venv
pip install /path/to/repo/checkout
python
Python 3.6.3 (default, Oct  4 2017, 06:09:05) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdax
```

Hope this helps.

**Comment by ksauln** [comment]
> It works for me. How I got it to work:
> 
> git clone https://github.com/danpaquin/gdax-python.git
> activate venv
> pip install /path/to/repo/checkout
> python
> Python 3.6.3 (default, Oct  4 2017, 06:09:05) 
> [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
    >>>import gdax
> Hope this helps.


This didnt seem to work for me

**Comment by ljcljc** [comment]
Hi, were you able to solve this issue? It works find with me in command line python, but when I put it in a script and tries to run the script, it has import error.
