### ISSUE TITLE
Websocket stops sending data but doesn't close connection

### ISSUE THREAD

**Issue by ankit1200** [danpaquin/coinbasepro-python#168]
Hi,

Previously mentioned in [issue #89 ](https://github.com/danpaquin/gdax-python/issues/89). The web socket stops sending data and seems to get stuck inside the on_error method in the websocket_client.py class. The print statement infinitely outputs: "socket is already closed. - data: None". Which means that the websocket doesn't really close and gets stuck in the _listen method even when there is no data coming through. We're currently testing a fix for this, where we close the current thread in the on_error method and then automatically restart the socket.

**Comment by mcardillo55** [comment]
Are you using the github version or the version from PyPi?

**Comment by ankit1200** [comment]
pretty sure I'm using the github version. Used the following command:
pip3 install git+https://github.com/danpaquin/gdax-python.git

**Comment by luismolina13** [comment]
I am also running into this issue. Is there a way to restart the socket if it gets caught up in the on_error method?

**Comment by mcardillo55** [comment]
> I am also running into this issue. Is there a way to restart the socket if it gets caught up in the on_error method?

I `raise` the Exception in the WebsocketClient on_error method(), then in my main thread run an infinite loop over a try: except: block, and for any exception I call WebsocketClient.close() and WebsocketClient.start()

**Comment by ankit1200** [comment]
I check every 15 seconds to see if there is data coming from the stream. If there is no data within 15 I close and start the stream again.
wsClient.close()
wsClient.start()

**Comment by JMedon** [comment]
@ankit1200 can you show your code how you implemented it? thanks in advance
