### ISSUE TITLE
any support for market orders or stop orders

### ISSUE THREAD

**Issue by k2ev** [danpaquin/coinbasepro-python#172]
How do we use this api to place market or stop orders?

**Comment by mattlisiv** [comment]
This can be done by passing in the type argument to the buy function to override the default order type, limit.

```python
auth_client.buy(type='market',
               size='0.01', #BTC
               product_id='BTC-USD')
```

The arguments map directly to the GDAX request:
https://docs.gdax.com/#place-a-new-order

**Comment by jackusc** [comment]
yep, and don't include a 'post-only' variable or it won't take it

**Comment by Rhodesyork** [comment]
How would we go about including a 'post-only' variable?

**Comment by Jaewan-Yun** [comment]
@Rhodesyork 
This is the official documentation for GDAX API: https://docs.gdax.com/#orders

You need to specify in the argument that {"post_only": True} when placing an order. This is an example of a limit buy, post-only order:
`
auth_client.buy(type='limit',
               size='0.01',
               price='10000',
               product_id='BTC-USD',
               "post_only": True)
`

Take a look at this code for a more explicit way to call specific orders in python: https://github.com/Jaewan-Yun/gdax-api-python/blob/master/gdax/private_client.py

**Comment by Rhodesyork** [comment]
Thank you so much! But does it not matter that Python’s True is not the same as JSON true?

**Comment by acontry** [comment]
It should look like this: `auth_client.buy(type='limit', size='0.01', price='10000', product_id='BTC-USD', 'post_only'=True)`
