### ISSUE TITLE
TImestamp expired error

### ISSUE THREAD

**Issue by andrewbain** [danpaquin/coinbasepro-python#174]
I am getting an error when requesting my account, public client request working ok

**Comment by mcardillo55** [comment]
Can you paste the output of the error?

**Comment by philipodonnell** [comment]
import gdax
    key = '***'
    b64secret = '***'
    passphrase = '***'
    auth_client = gdax.AuthenticatedClient(key, b64secret, passphrase, api_url="https://api-public.sandbox.gdax.com")
    print(auth_client.get_accounts())

Connected to pydev debugger (build 163.8233.8)
{'message': 'request timestamp expired'}

**Comment by philipodonnell** [comment]
I have the same issue and its driving me insane. I get the same error with the node apis and the python ones. The API keys are definitely correct. I get the same error using the sandbox api and the live api.

**Comment by acontry** [comment]
This could be an issue with your machine's local time, since a timestamp is used in authentication. [GDAX offers an endpoint](https://docs.gdax.com/#time) to get their timestamp, which you can use to compare against your local machine and check for any weird problems.

**Comment by philipodonnell** [comment]
import time
    import gdax
    public_client = gdax.PublicClient()
    print(time.time(), public_client.get_time())

yields

    1512978159.8325033 {'epoch': 1512978191.837, 'iso': '2017-12-11T07:43:11.837Z'}

The iso time is correct except my timezone is EST. The epoch and my computer time don't match exactly, but surely that's due to the time zones? Does this library require the computer time to be in GMT+0?

**Comment by philipodonnell** [comment]
I set my computer to GMT+0 just to test but it didn't work either.

**Comment by acontry** [comment]
Looks like you have about 30 seconds difference between your computer and GDAX. Maybe sync your local time to internet time and retry? Just my best guess.

**Comment by andrewbain** [comment]
I just reset my time using auto setting for my area and it now seems to work

**Comment by philipodonnell** [comment]
1513008013.3986995 {'epoch': 1513008013.502, 'iso': '2017-12-11T16:00:13.502Z'}

I didn't do anything but now it works. Did my clock suddenly sync overnight? What are the odds of that?

**Comment by acontry** [comment]
@phillipodonnell Your clock usually does sync overnight :)
