### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by chrischris292** [danpaquin/coinbasepro-python#191]
PR out here https://github.com/danpaquin/gdax-python/pull/197

I like this framework, but when I've tried to write my own trading strategy on top of this, there are a few performance bottlenecks in the orderbook that can be improved. 

Each price level in the RBTree bids and asks book should be an ordered dictionary where key is the id and value is the order. Will give O(1) access to top level and will give O(1) removal/insertions. This gives significant improvements over a few O(n) calls.

https://github.com/danpaquin/gdax-python/blob/fe727f57476bb396b1816d9666429d93bfe2d561/gdax/order_book.py#L103

This O(n) operation doesn't do anything
https://github.com/danpaquin/gdax-python/blob/62b7b808914f3573ca2ac10c0e59159e34e99d08/gdax/order_book.py#L188

**Comment by danpaquin** [comment]
I believe this was fixed via #272.  I apologize for not merging your PR, but I liked the idea of getting away from RBTrees for this high level package.
