### ISSUE TITLE
Version on PIP needs to be updated

### ISSUE THREAD

**Issue by CreaoticX** [danpaquin/coinbasepro-python#208]
If you install this using pip it's and old version that is out of date.  I don't know all of the features that are missing, but at least one of them is the ability to subscribe to specific channels.  I fixed this by just going in and copying and pasting the new files.  Not sure how to get pip to get the new files.  I'm pretty sure this is what's causing #205 at least.

**Comment by philhudson91** [comment]
+1 please do

**Comment by smalbadger** [comment]
I'm sorry, I'm not familiar with installing python modules manually. Did you just clone the repository somewhere and not actually install the gdax module?

**Comment by CreaoticX** [comment]
If you install with pip it installs in your Python installation folder.  You can google to find the location for your operating system.  I just went in and copied the files from github into that folder manually.  I guess you could do a git clone too, but I haven't tried it.

**Comment by obixmt** [comment]
@CreaoticX 
Thanks for pointing in the right direction, this allowed me to get the Order Book example working.

I'm on a Debian system and had to do the following as root:
> pip uninstall gadx
> rm -fvr /usr/local/lib/python2.7/dist-packages/gdax
> rm -fvr /home/<username>/.local/lib/python2.7/site-packages/gdax
> pip install git+https://github.com/danpaquin/gdax-python@master
the copy in my /home path was the one that I'd been missing, not sure how it got there?  Hope this is helpful to someone, thanks!

**Comment by danpaquin** [comment]
This will be completed after PR #260 is finalized and tests are passed.

**Comment by uclatommy** [comment]
@CreaoticX, you can use pip to install directly from github like so:
`pip install git+https://github.com/danpaquin/gdax-python.git`

**Comment by wileybaba** [comment]
I've followed this exactly and have all the required dependencies install and I'm still getting:   

```
File "gdax_pull.py", line 6, in <module>
    public_client = gdax.Public_Client()
AttributeError: module 'gdax' has no attribute 'Public_Client'
```

Any ideas? I'm running OSX
