### ISSUE TITLE
OrderBook Logging

### ISSUE THREAD

**Issue by tanaytrivedi** [danpaquin/coinbasepro-python#222]
Hi,
I see a facility to log OrderBook Messages as received into a pickle file. It seems to be instantiated when the OrderBook is, judging from the code:
<img width="468" alt="screen shot 2018-01-07 at 5 16 25 pm" src="https://user-images.githubusercontent.com/19849991/34654795-879f530c-f3ce-11e7-98c3-e1ea12e72992.png">
I am only aware that it is for this purpose from a line later in the code in on_message:
<img width="338" alt="screen shot 2018-01-07 at 5 19 49 pm" src="https://user-images.githubusercontent.com/19849991/34654842-0027e186-f3cf-11e7-9797-6a1a8f88e591.png">
However, I am not sure what to pass to the instantiation to make this function. Do I pass the name of the pickle file I want to use? Something like this?
<img width="1114" alt="screen shot 2018-01-07 at 5 17 53 pm" src="https://user-images.githubusercontent.com/19849991/34654820-b99c6ab6-f3ce-11e7-8e31-2b6d292889b5.png">
This is a really useful feature, and I want to take advantage of it. Please let me know if you've figured this out.
Thanks,
Tanay Trivedi

**Comment by Prophacy** [comment]
log_to needs to be a file object
`log_to = open('book.pkl', 'w')`

I am not very familiar with this package yet, but at first glance it doesn't appear to handle closing of that file either, so after you close the socket or are done with writing to the file, you need to call `log_to.close()`.

I think I would like the class edited to be able to pass a string "book.pkl" to init and have the class itself deal with opening, writing to, and closing the file.

If we get some more input here I would be willing to submit a pull request (would be my first PR on github) and add that functionality in. as it feels a little "loose" at this point, or at least add a comment documenting what types the init function is looking for. Either solution would clear up this problem in the future.

**Comment by tanaytrivedi** [comment]
Thanks. I'll leave it open until we get some clarification. For now, I realized we can just log the WebsocketClient Updates in the on_message function. Or, if people prefer the resultant best bid and best ask, they can log in the on_message of OrderBook.

**Comment by danpaquin** [comment]
In terms of supporting third-party projects here, we currently have an implementation for MongoDB, but I would prefer to deprecate that in favor of adding Pandas dataframes and CSV's.

I've listed this as a feature request.
