### ISSUE TITLE
OrderBook Broken in Pip v 1.0.6 

### ISSUE THREAD

**Issue by chesswiz16** [danpaquin/coinbasepro-python#227]
Version of OrderBook in 1.0.6 install via pip (latest?) calls PublicClient with a product_id argument.

**Comment by dude8604** [comment]
Same here

**Comment by Prophacy** [comment]
The pip install of this package needs to be updated.  https://github.com/danpaquin/gdax-python/issues/208 .. try to use the answer at the end of that issue and see if this issue is fixed

**Comment by tanaytrivedi** [comment]
If you install from the current Github version it works. Well mostly, there is still some stuff that is not working for me, but that's a different issue see #228
