### ISSUE TITLE
Weird Websocket Failure

### ISSUE THREAD

**Issue by tanaytrivedi** [danpaquin/coinbasepro-python#228]
Hi,
So another peculiarity of running the OrderBook in python 2.7 (haven't exactly checked if this happens in 3.4)...

I get a failure with some consistency from the websocket module in python. It looks a little bit like this:
<img width="480" alt="screen shot 2018-01-09 at 11 05 39 am" src="https://user-images.githubusercontent.com/19849991/34730337-16b33fc2-f52d-11e7-93a4-9b4760d2989f.png">
This is the general format that the OrderBookConsole runs on, and I needed something that ran the same way: it needs to do something every time a message was logged.

OrderBookProcess is a class I wrote that extends OrderBook. The error seems to be generated from the websocket module in Python. Does anybody why this happens? It happened consistently every 10 or more minutes, so I wrote a workaround that stores the data I wanted from OrderBookProcess and then reboots the OrderBook every 5 minutes: 
<img width="522" alt="screen shot 2018-01-09 at 11 06 25 am" src="https://user-images.githubusercontent.com/19849991/34730368-2c2dfed2-f52d-11e7-83d6-44f45ed9c9d4.png">

However, this didn't help, and just increased the frequency of my failure. The second failure below happened immediately after rebooting. This error code DOES NOT trigger on_close, meaning that its not an error per se and the cell keeps running but does not log any additional data.

Is this happening to nobody else? Would appreciate the help.

**Comment by danpaquin** [comment]
Please reopen this issue if it persists.
