### ISSUE TITLE
AttributeError: module 'gdax' has no attribute 'WebsocketClient'

### ISSUE THREAD

**Issue by BattlestarPegasus** [danpaquin/coinbasepro-python#247]
Fresh install and getting this weird error after playing with the websocket.  Now I cant import gdax without this error.  I tired pip uninstall/install gdax and tried re-install the requirements with no luck.  The only fix is a complete reinstall or new environment in python

**Comment by BattlestarPegasus** [comment]
Interestingly enough I fixed the error by running 'import gdax' script on my C drive.  I was testing on my second drive and had some issues.

**Comment by mcardillo55** [comment]
Seems like it may be something in your environment. Did you perhaps have another file named gdax.py in your working directory? Are you still having this issue?

**Comment by eeyhp2** [comment]
I am also having this issue. Fresh python installation.

**Comment by eeyhp2** [comment]
Found the problem - if the file you are using is named gdax.py, it will cause this error.

**Comment by gfranco008** [comment]
I fixed the issue by uninstalling `pip uninstall websocket-client` and reinstalling it. `pip install websocket-client==0.40.0`
