### ISSUE TITLE
bintrees is deprecated, suggests sortedcontainers

### ISSUE THREAD

**Issue by grantjenks** [danpaquin/coinbasepro-python#297]
Hi, I'm the author of `sortedcontainers` and noticed that you're using the `bintrees` module. If you look at the PyPI page for [bintrees](https://pypi.org/project/bintrees/) then you'll see that development has stopped and `sortedcontainers` is recommended instead.

I'd love to see `sortedcontainers` used in more places. If I created a pull request which replaced `bintrees` with `sortedcontainers`, would that be merged?

**Comment by alimcmaster1** [comment]
Hey Grant,

Ive used sortedcontainers a little before so I’m happy to submit a PR. Would be a good opportunity for me to understand sorted containers better. You okay with this?

Would be great if you could review our implementation too.  @danpaquin any concerns on this ?

**Comment by alimcmaster1** [comment]
Actually i noticed this has already been done and merged to master.
https://github.com/danpaquin/gdax-python/pull/272/commits

Whenever the latest version is released to PyPI this will be fixed.

Thanks,

**Comment by grantjenks** [comment]
Those changes look good but I think they missed one spot in `setup.py`: https://github.com/danpaquin/gdax-python/blob/master/setup.py#L6
