### ISSUE TITLE
OrderBook is broken as of version 1.0.6

### ISSUE THREAD

**Issue by dhanunjayalakshmi** [danpaquin/coinbasepro-python#298]
I have created a test script following the instructions given in the Readme.md file.

`order_book = gdax.OrderBook(product_id='BTC-USD')
    order_book.start()
    time.sleep(10)
    order_book.close()`

I am getting the below error:
`Traceback (most recent call last):
  File "gdax_collector.py", line 12, in <module>
    order_book = gdax.OrderBook(product_id='BTC-USD')
  File "~/venv/lib/python3.6/site-packages/gdax/order_book.py", line 21, in __init__
    self._client = PublicClient(product_id=product_id)
TypeError: __init__() got an unexpected keyword argument 'product_id'
`

**Comment by JoaoAparicio** [comment]
If you download the latest version (as opposed to just doing `pip install`), it works.
