### ISSUE TITLE
Different than others I've seen but same problem: AttributeError: module 'gdax' has no attribute 'public_client'

### ISSUE THREAD

**Issue by PyFiSciFi** [danpaquin/coinbasepro-python#302]
I am using Anaconda (Spyder) to run Python, and I have gdax downloaded but it doesn't detect authenticatedclient or publicclient as being attributes of gdax. Multiple others I have seen somehow fixed the problem by changing the name of their script? But That is not the cause of my problem. In fact, I think mine installed incorrectly because I found the location of the GDAX scripts and authenticatedclient and publicclient are not there. Only orderbook, trader, utils, and a couple others are. I have also used IDLE to run Python, and it works fine with GDAX and the public client. I found the location of GDAX scripts with IDLE and it did have the correct scripts there. I tried moving those to the location with the gdax scripts for anaconda but it did not fix the problem. 
I'm assuming this is an installation issue that can be fixed with a simple command or upgrade command or something but I'm not a master at this. Any suggestions? Thanks.

**Comment by PyFiSciFi** [comment]
Okay yeah, fixed it. I went to uninstall and reinstall gdax and my computer didn't even detect gdax, so I installed it (again) and it worked. Not sure how it managed to do that.

**Comment by PyFiSciFi** [comment]
Update: everytime I install/uninstall/reinstall GDAX, something isn't working. After a fresh uninstall and reinstall and starting Spyder, now my computer still doesn't detect that GDAX exists and says that GDAX isn't a module. I am pip installing it from Anaconda prompt. Could it be that my previous installations for IDLE in other directories (not touched by these installations) could be messing with it? Idk but I def need help/ideas. Idk how to make sure I have the correct thing installed and in the correct location. I also installed all the dependencies listed on this github profile/site thing.

**Comment by SorenJ89** [comment]
how are you installing it? i know it doesn't say in the MD, but what worked for me was 
"pip install git+https://github.com/danpaquin/gdax-python.git"

also discussed here:
https://github.com/danpaquin/gdax-python/issues/208
