### ISSUE TITLE
auth client KeyError on qpython3.6

### ISSUE THREAD

**Issue by garagesteve** [danpaquin/coinbasepro-python#305]
QPython v2.2.4-8 running Python 3.6

Problem code:
dollarInd = str(auth_client.get_accounts()[account])

Error:
KeyError: 0

API credentials and permissions are correct. Works on my pi and windows laptop with regular py3, but not on my android phone with qpy3.6

What the haerr damn guy

**Comment by danpaquin** [comment]
Thanks for reaching out.  Would you please post your entire script including the full error code? The issue could be a number of things with this context.
