### ISSUE TITLE
Post only buy/sell option?

### ISSUE THREAD

**Issue by mattdornfeld** [danpaquin/coinbasepro-python#307]
I see in the new [Coinbase Pro api](https://support.pro.coinbase.com/customer/en/portal/articles/2945313-overview-of-order-types-and-settings-stop-limit-market-?b_id=17474) there is an option for post only that ensures a limit order will not incur and taker fees. Are there any plans to include this in the Python lib?

**Comment by s-kent** [comment]
It is already included both for gdax and coinbase_Pro Apis. you need to set the post_only tag to 'true'. e.g: auth_client.buy(price=p,size=s,product_id='BTC-USD',type='limit',post_only='true)'

**Comment by danpaquin** [comment]
Please let us know if you any any additional questions on this
