### ISSUE TITLE
coinbase pro support?

### ISSUE THREAD

**Issue by PeishuoYu** [danpaquin/coinbasepro-python#308]
GDAX is going to depreciated, will this package be changed to support coinbase pro?

**Comment by zgdaf** [comment]
I am not sure if there are plans to support coinbase pro, but here is what
Coinbase said to replace the URL with the[ coinbase Pro ur](https://www.reddit.com/r/BitcoinMarkets/comments/8sv3cn/gdax_transitions_to_coinbase_pro_june_29th/)l.
"There will be no disruption to the gdax.com API during this time. GDAX APIs will continue to function until December 31, 2018. We encourage Coinbase Pro users to begin migrating their API usage away from api.gdax.com to api.pro.coinbase.com. Coinbase Pro is currently live and we encourage all users to update their bookmarks and try our upgraded trading experience today."

Replace the url in the gdax.AuthenticatedClient method and see if it works.

**Comment by acontry** [comment]
FYI I'm working on a Coinbase Pro fork of this project which is already live on PyPI: https://github.com/acontry/coinbasepro

**Comment by Vacant0mens** [comment]
@acontry will you be adding websocket connections to your project?

**Comment by acontry** [comment]
Eventually I plan to, yes.

**Comment by Vacant0mens** [comment]
When you get there, I would recommend going with  [pypi's](https://pypi.org/project/websockets/) `websockets` (plural, not singular like what's in gdax-python)
I'm not sure what is included in gdax-python, but it doesn't seem as easy to implement.

**Comment by acontry** [comment]
Thanks, I'll keep that in mind. I think the challenge for a library is to present an interface to cover all users' use cases nicely, and I haven't scoped that out yet for the websocket API. I have an asyncio-based orderbook I run on my own, but it's definitely not library-quality code :)

**Comment by Vacant0mens** [comment]
Sounds good. I'll keep an eye on your project 😃

**Comment by SorenJ89** [comment]
I replaced the references from gdax api to coinbase api in this project and it seems to work fine. So i dont want to be rude, but is a fork necessary? i mean spreading the effort over two projects instead of one.
or is this project dead?

**Comment by lirenz** [comment]
I like this library for it's simplicity. My main gripe is that the websocket client should be separate from the orderbook (which should only exist to process messages from 1 socket). I submitted an L2 order-book that somewhat did that a while back.

The lib should also ditch the MongoDB dependency. The method of saving data should be left up to the person using the lib.

**Comment by acontry** [comment]
@SorenJ89 The short answer is there are a number of improvements I'd like to make to the project, some of which are not PRs (and others are significant improvements that have been submitted here and haven't made it into master).

@lirenz I'm in agreement on all points.

**Comment by danpaquin** [comment]
I apologize to this community that I have not had time to push code to master or update pip for a few months, and currently looking for contributors to manage the PR's in a decentralized fashion.

@acontry I would appreciate your help to prioritize PR's for this project.
@everyone feel free to reach out to me directly for collaborator access.
