### ISSUE TITLE
Continuous Integration Set up

### ISSUE THREAD

**Issue by alimcmaster1** [danpaquin/coinbasepro-python#312]
What are peoples thoughts on setting up tests to run on travis and have some form of CI? Im happy to add the config yaml file.

**Comment by danpaquin** [comment]
I'd be happy to review a PR regarding this.

**Comment by uclatommy** [comment]
Yes please! I have been using this project for a few months and it has been a blessing to be able to have it, but it seems like some functionality occasionally regresses on new releases due to inadequate unit tests and CI.

**Comment by carlomazzaferro** [comment]
Would travis be ok @danpaquin ? I can work on a prototype as I've been working a bit with it for other projects.

**Comment by alimcmaster1** [comment]
Thanks @carlomazzaferro , ive already submitted a PR for this as there isn't much to it. Setting up something simple for now

**Comment by danpaquin** [comment]
This has been implemented via #318 , but not ironed out.  Please feel free to submit a PR for any improvements!
