### ISSUE TITLE
cancel_after not working 

### ISSUE THREAD

**Issue by AlexFine** [danpaquin/coinbasepro-python#317]
I'm running:
 `auth_client.buy(price = str(price), #USD
                   order_type='limit',
                   size = str(volume), #BTC
                   product_id = currency + '-USD',
                   tif = 'GTT',
                   cancel_after = 'min',
                   post_only = 'true')`
and the trade is put on the order books, however, the cancel_after is not working. It never cancels. I've also tried the same thing with `cancel_after = '1'` and it didn't work either. 

I presume I'm doing something wrong. Can anyone spot it?

Any help is appreciated!

**Comment by danpaquin** [comment]
After taking a second look, this could be related to an exchange issue, since all request parameters are sent together.  In my adhoc test, if any data reaches the exchange servers, all data hits the server.

Lastly, are you using the current repository?  If not, what version are you running?

**Comment by chrisjbroeren** [comment]
There seems to be some confusion on the `tif = ` (a.k.a `time_in_force = `) argument. Coinbase list the argument as `time_in_force`. I made a super basic fix (that failed in some CI pipeline) [here](https://github.com/danpaquin/coinbasepro-python/pull/323).

My work around for the time being is just to have both `tif` and `time_in_force` set to `= "GTT"`

**Comment by danpaquin** [comment]
Great find! Merged and will close this out after pip is updated.

**Comment by alimcmaster1** [comment]
Thanks Chris,

We have recently just introduced CI on travis and that was the first build that ran. I’ll fix this today.

Thanks,

Alistair

**Comment by AlexFine** [comment]
@chrisjbroeren that works perfectly, thanks!!

**Comment by danpaquin** [comment]
this has been resolved in pip version 1.1.3
