### ISSUE TITLE
Historic rates time interval not working

### ISSUE THREAD

**Issue by kevinkatzke** [danpaquin/coinbasepro-python#322]
Hey,

I try to request historic rates for BTC-USD for a specific time interval:

```
servertime = cbpro.get_time()
endtime = datetime.datetime.strptime(servertime['iso'],'%Y-%m-%dT%H:%M:%S.%fZ')
granularity = 300
count = 3
delta = granularity * count 
starttime = endtime - datetime.timedelta(seconds=delta)
starttime = starttime.isoformat()
endtime = endtime.isoformat()

data = cbpro.get_product_historic_rates(str(instrument), start=str(starttime), end=str(endtime), granularity=int(granularity))
```

The requested time interval is:

```
Requested starttime :    2018-08-26T12:00:31
Requested endtime :      2018-08-26T12:15:31
```

The problem is that this returns anything but what is expected. Insted of 4 results I get 26. None of those values lies within the defined time interval. The most recent value  is indeed older than my starttime.

When I take my time strings and I past them in this form: https://gdaxurl.surge.sh/ I correctly get the result as expected. Here is the HTTP request and its output:

https://api.gdax.com/products/BTC-USD/candles?start=2018-08-26T12:00:31.00000Z&end=2018-08-26T12:15:31.00000Z&granularity=300

How come the HTTP request delivers the correct values while the cbpro request does not?

----

**I've installed the most recent version of cbpro 1.1.1 from github via pip.**

**Comment by danpaquin** [comment]
Please read through #321 and see if the UTC issue is at fault here.

If not, please let us know if you are still experiencing this issue after updating your package.

**Comment by kevinkatzke** [comment]
@danpaquin I've updated my cbpro package to the latest git master and I've now version 1.1.2 installed. I'm still facing the same issue.

**Comment by danpaquin** [comment]
I looked into this and getting correct results.  The request url that the library is producing from the params is below.  Clearly, this is not the exact request in your example, but returns the same data.  Please let me know if you continue having issues here and I can dig deeper if you provide more information.

Request:
`
https://api.pro.coinbase.com/products/BTC-USD/candles?start=2018-08-26T12%3A00%3A31&end=2018-08-26T12%3A15%3A31&granularity=300
`

Response:
`
[[1535285700, 6700, 6700.01, 6700, 6700.01, 0.48444962999999996],
 [1535285400, 6700, 6704.75, 6704.41, 6700, 17.78793604],
 [1535285100, 6699.64, 6710.73, 6699.65, 6704.39, 43.122801550000005],
 [1535284800, 6696.9, 6702.98, 6696.98, 6699.64, 8.263433840000001]]
`

**Comment by kevinkatzke** [comment]
@danpaquin The Error still exists. Ist seems to be a bug indeed. Here's the response from Coinbase Support.

Hi Kevin,

Thank you for contacting Coinbase Pro Support.

I looked through your code and it seems to be fine. I was still able to reproduce the error using the same code on the cbpro endpoint.

I tested it on our still-active GDAX endpoints with the same code and it worked fine. I will submit this for our team for review, but in the meantime, we suggest using the unofficial GDAX python library. The GDAX endpoints will be operational until the end of the year.

I hope this helps. If you have any questions, please let me know!

Robert
Coinbase Pro Support Team

**Comment by danpaquin** [comment]
I hope this link works, but I could not solve this issue with the following either:
https://repl.it/repls/CraftyKnownProject

My guess is the API is treating anything with an endtime ~= servertime to be a default request rather than a specific date range, but this is far fetched.

Leaving this open for someone else to consider.
