### ISSUE TITLE
websocket client error with json - "data: None" 

### ISSUE THREAD

**Issue by penguinshin** [danpaquin/coinbasepro-python#331]
Was running the mongodb example for a few products last night and when I woke up about 8 hours later I noticed the script had terminated with this error: 

> Expecting value: line 1 column 1 (char 0) - data: None

Any ideas?

**Comment by kkuette** [comment]
Take a look at #211

**Comment by penguinshin** [comment]
Thank you. For anyone who has a similar issue, the way I solved it was by subclassing with a custom on_close function;

`def on_close(self):
		if self.should_print:
			print("\n-- Socket Closed --")
		if self.should_restart:
			self.start()
			print("\n-- Socket Reopened --")`

So that when the client closes either due to error or otherwise, it will automatically restart.
