### ISSUE TITLE
Transition From gdax to cbpro

### ISSUE THREAD

**Issue by bristola** [danpaquin/coinbasepro-python#334]
Is there any where that has all changes that occur when changing the API from gdax to coinbase pro?
If so, it may be helpful to put this information in the README or a link to the changes. Those transitioning their programs from gdax to the cbpro may find this helpful to see what changes they need to make to their existing programs originally written with gdax.

**Comment by skyl** [comment]
@bristola did you ever upgrade and take any notes?
