### ISSUE TITLE
Coinbase Pro API now requires a Product ID or an Order ID

### ISSUE THREAD

**Issue by TheKeyboardKowboy** [danpaquin/coinbasepro-python#335]
From Coinbase Pro API:

DEPRECATION NOTICE - Requests without either order_id or product_id will be rejected after 8/23/18.

get_fills() without a product id or a product id no longer functions.

**Comment by yiwensong** [comment]
get_fills raises a ValueError when both order_id and product_id are None. this seems to be consistent with the documentation.

**Comment by mcardillo55** [comment]
This was addressed by 7d993fc5cdacbc45e04a54653c9df90105549e76. Closing.
