### ISSUE TITLE
Order status definitions (received, open, pending, active, done, settled)?

### ISSUE THREAD

**Issue by uclatommy** [danpaquin/coinbasepro-python#336]
I tried looking for more precise definitions of each order status but could not find it either on this repo or the official API docs. Does anyone have knowledge of the precise definitions? Here's my understanding so far (I've annotated with ??? where unsure):
1. received: Not yet on order book, but has been received by Coinbase pro and is in process of being placed on the order book
1. open: Has been received and is on order book (???)
1. pending: Is open and is waiting for fills (???)
1. active: Is open and has been partially filled (???)
1. done: Has been canceled with or without partial fills (???) or has completed with all fills. May or may not yet have settled status.
1. settled: An order that is done and taken off the order book.

**Comment by mcardillo55** [comment]
I don't see anywhere where this is documented either. Closing this since it's not really an issue with the library.
