### ISSUE TITLE
Coinbase dropping support for v1 of API on 12/1/2018

### ISSUE THREAD

**Issue by TheKeyboardKowboy** [danpaquin/coinbasepro-python#340]
Just received notice that as of 12/1/2018 all API requests now need to utilize the v2 API specification.

It doesn't look like this client is using v2 as of yet.  I have not investigated what, if any, changes are required beyond calling the new endpoint: 'https://api.coinbase.com/v2/'

Just wanted to post this as a notice.

**Comment by yiwensong** [comment]
there is now an official coinbase clientlib:

https://github.com/coinbase/coinbase-python

**Comment by lirenz** [comment]
I believe coinbase != coinbase pro (which is the exchange).

**Comment by yiwensong** [comment]
yeah, I got confused. I edited my comment to be less confusing

**Comment by mcardillo55** [comment]
Closing since this is related to the Coinbase library, not Coinbase Pro.
