### ISSUE TITLE
This is giving me the error 'request timestamp expired' on Centos7

### ISSUE THREAD

**Issue by Landl3ss** [danpaquin/coinbasepro-python#344]
Hello,

I'm getting the error {'message': 'request timestamp expired'}.

I've tested this on a Windows 10 python 3.6 shell it works, I've also tested this out Mac OSX python 3.7. It works on those OS'. But when working on my Centos7 server I get this error.

My code is just to test out the program:

```
import cbpro

api_secret = [my api secret]
api_key =[my api key]
api_pass =[my api passphrase]

ac = cbpro.AuthenticatedClient(api_key, api_secret, api_pass) # even with the sandbox URL it gives the same error
ac.get_accounts()
```
>>> {'message': 'request timestamp expired'}

**Comment by noah222** [comment]
This can happen when your system clock is not in sync with coinbase servers. Have you checked that your clock is properly synced?

**Comment by mcardillo55** [comment]
No response. Closing.
