### ISSUE TITLE
Add class constants

### ISSUE THREAD

**Issue by matts80** [danpaquin/coinbasepro-python#366]
Idea to add parameter constants to avoid typos when calling functions.  

Example:

```python
class cbpro:
    ORDER_LIMIT = 'limit'
    ...
```

Then when calling the `buy` or `sell` method:

```python
auth_client.buy(order_type=cbpro.LIMIT)
```

**Comment by noah222** [comment]
A = auth_client.buy(order_type="limit") is less clunky in my opinion. What kind of typos are there with such sort names?

**Comment by matts80** [comment]
Looking through the API, they are all pretty short.  Probably no need for it.
