### ISSUE TITLE
How to get order ID of order being placed?

### ISSUE THREAD

**Issue by powertradercrypto** [danpaquin/coinbasepro-python#376]
How do I get the return data from placing orders?

**Comment by noah222** [comment]
ThisOrderQuery = auth_client.buy(.....)
print(ThisOrderQuery)

**Comment by powertradercrypto** [comment]
Does it send the order on declaration or print?

**Comment by noah222** [comment]
print is just showing you what information was received and saved in the variable. If you want to get specific information you can do something like print(ThisOrderQuery['id'])

**Comment by powertradercrypto** [comment]
Ok thanks! This will help me out so much..

**Comment by noah222** [comment]
Great, I've been using this API for more than a year, so if you have other questions I can try to help.

**Comment by powertradercrypto** [comment]
Thanks, yeah ive been using it since gdax days, but recently totally overhauled my autotrader and have been encountering weird errors. I think I have everything good now though.... hopefully, cause riches await!

**Comment by noah222** [comment]
You just asked me what a print statement is doing, and that kind of
question only comes from someone who is not a programmer. I can't imagine
expecting to make money without understanding the API or basic print
statements.

**Comment by powertradercrypto** [comment]
I asked you if the order command went through to coinbase on the variable declaration or on the print statement. 
You misunderstood my question, so I won't hold your a-holeness against you man. I really appreciate the help you have given me. Thanks. Have a good day.
