### ISSUE TITLE
time_in_force='FOK' not working

### ISSUE THREAD

**Issue by powertradercrypto** [danpaquin/coinbasepro-python#377]
auth_client.place_limit_order(product_id=coins[coinselector], side='buy', price=buy_price, size=buy_size,time_in_force='FOK')

will not place an order but

auth_client.place_limit_order(product_id=coins[coinselector], side='buy', price=buy_price, size=buy_size)

will place an order

**Comment by noah222** [comment]
It will only place the order if the order price matches the current price specified, else it is KILLED. so It will fill at the price you are sending only if there is enough volume to fill the order. And it will be immediately filled as a taker order.

**Comment by powertradercrypto** [comment]
Ok thanks, I misunderstood how FOK worked

**Comment by noah222** [comment]
It's basically a way to buy a certain amount but not buy any if you can't get the whole amount you want to buy.

**Comment by powertradercrypto** [comment]
Yeah i thought it meant the order would just stay open unless fully filled... would be way better

**Comment by noah222** [comment]
that's Good til cancelled

**Comment by powertradercrypto** [comment]
Yeah but that allows for partial fills

**Comment by noah222** [comment]
I see partial fills as a good thing. it requires a bit more technical
set-up to track what happened, but the flexibility is worth it. You could
try FOC without a price, I'm not sure what happens in that case. It seems
like it would fill just like a market order.
