### ISSUE TITLE
How to program max Buy or Max Sell?

### ISSUE THREAD

**Issue by MrDevBC** [danpaquin/coinbasepro-python#392]
Hi,
I'm trying to find out a way to do Max buy or Max Sell with this:

 auth_client.place_market_order(product_id='BTC-USD', side='buy', funds=Max_Funds)
 auth_client.place_market_order(product_id='BTC-USD', side='sell', funds=Max_Funds)

any help would be appreciated

**Comment by danpaquin** [comment]
You will want to use the endpoint to get account info: `auth_client.get_accounts()`

With this info you can determine your max available funds.

**Comment by MrDevBC** [comment]
I try that, but when I try to purchase it.. it saying the funds is to accurate.

**Comment by MrDevBC** [comment]
> 
> 
> You will want to use the endpoint to get account info: `auth_client.get_accounts()`
> 
> With this info you can determine your max available funds.

I try that, but when I try to purchase it.. it saying the funds is to accurate.

**Comment by danpaquin** [comment]
There must be a specification on the precision which is allowed.  Try truncating/rounding to only allow 8 digits after the decimal.

https://docs.python.org/3/tutorial/floatingpoint.html
