### ISSUE TITLE
Invalid order_type stop

### ISSUE THREAD

**Issue by bryanminorphd** [danpaquin/coinbasepro-python#405]
When using: place_stop_order() itis returning - 'Invalid order_type stop'

What does this mean? How is possible to do a true "stop" order for Coinbase?

**Comment by bryanminorphd** [comment]
Looking at Coinbase documentation it looks like there is only 'market' and 'limit' order types: https://docs.pro.coinbase.com/#orders

**Comment by QuentinJcb** [comment]
#370 should fix this issue

**Comment by mcardillo55** [comment]
#370 merged.
