### ISSUE TITLE
'request timestamp expired'

### ISSUE THREAD

**Issue by gilmotta** [danpaquin/coinbasepro-python#413]
Hello Gentlemen,
Thanks for creating such a nice library. It is very easy and intuitive.

I came across an issue. I open the connection to the server and authenticate without problems.
auth_client = cbpro.AuthenticatedClient(COINBASE_KEY, COINBASE_BASE64_SECRET, COINBASE_PSWD,api_url="https://api-public.sandbox.pro.coinbase.com")

I'm able to get my balance during the first few minutes but then I start getting the error in the subject of this issue.

To get my balance, I do as follows:

        coinbase_accounts = auth_client.get_accounts()

        print(str(len(coinbase_accounts)))
        if "message" in coinbase_accounts :
            print(f"coinbase_accounts error! {coinbase_accounts }")
            return

The error message in JSON format is: {'message': 'request timestamp expired'}

Has anyone seen this issue? is there a fix or workaround?

I appreciate if you shed any light to help me.

Best Regards,

**Comment by mtingers** [comment]
Sounds similar or a duplicate to this issue:
https://github.com/danpaquin/coinbasepro-python/issues/407#issuecomment-749099480

I haven't tried the sandbox in a while, so the issue may be different.  Maybe try it in a loop outside of the sandbox to see if you get the same behavior? Example:

```python
while 1:
    coinbase_accounts = auth_client.get_accounts()
    print('coinbase_accounts:', coinbase_accounts)
    if 'message' in coinbase_accounts:
        break
    time.sleep(120)
```

**Comment by gilmotta** [comment]
I would like to contribute to this community. I am running my bot on a Virtualbox VM Windows 10 guest and the issue here is caused by the VM clock drifting from the host clock. I already have plans to improve the VM etc. but before I implement a better environment, I have a python script running in parallel updating the clock every 4 seconds based on a list of Internet Time Servers. Since I implemented this workaround I have not missed one single get_account update. The code I used as the basis for my workaround can be found here:
https://gist.github.com/gilmotta/200dfc135b00b3e97ed79b711de6009a
I hope this helps whoever steps on this mine field that has nothing to do with the coinbasepro libs. The coinbasepro libs run perfectly fine.

I tried configuring Windows 10 to update based on Internet time, under Date/Clock there is such option but believe it did not work for some reason Windows 10 Internet time is only programmed to sync up once every few **minutes**. Not until a implemented the workaround I was able to get reliable responses from Coinbase API.

**Comment by gilmotta** [comment]
> Sounds similar or a duplicate to this issue:
> [#407 (comment)](https://github.com/danpaquin/coinbasepro-python/issues/407#issuecomment-749099480)
> 
> I haven't tried the sandbox in a while, so the issue may be different. Maybe try it in a loop outside of the sandbox to see if you get the same behavior? Example:
> 
> ```python
> while 1:
>     coinbase_accounts = auth_client.get_accounts()
>     print('coinbase_accounts:', coinbase_accounts)
>     if 'message' in coinbase_accounts:
>         break
>     time.sleep(120)
> ```

Thank you!
