### ISSUE TITLE
Trailing Stop - Dynamically updating existing positions

### ISSUE THREAD

**Issue by KitHaywood** [danpaquin/coinbasepro-python#467]
Hi There, 

Is it possible to create a position - 

```python
auth_client.buy(price='100.00', #USD
               size='0.01', #BTC
               order_type='limit',
               product_id='BTC-USD')
```
And then somehow update that position with a trailing stop at user-defined intervals?

**Comment by Mat-C-uk** [comment]
I would track it in python and when the actual sell or buy needs to execute, call the sub with the buy or sell in.


Mat

Matthew Carpenter
07715370228


From: KitHaywood ***@***.***>
Date: Monday, 16 May 2022 at 19:14
To: danpaquin/coinbasepro-python ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [danpaquin/coinbasepro-python] Trailing Stop - Dynamically updating existing positions (Issue #467)

Hi There,

Is it possible to create a position -

auth_client.buy(price='100.00', #USD

               size='0.01', #BTC

               order_type='limit',

               product_id='BTC-USD')

And then somehow update that position with a trailing stop at user-defined intervals?

**Comment by KitHaywood** [comment]
Sweet understood - was a long shot
