### ISSUE TITLE
API guiding principles in refactoring

### ISSUE THREAD

**Issue by acontry** [danpaquin/coinbasepro-python#60]
I just wanted to share some details of the guiding principles I'm using in refactoring the API:
* The Python API should be similar to the official APIs.
* The API should be Pythonic. We're improving on this front already with naming conventions. Function signatures and general flow control leave room for improvement yet.
* The API should be self-documenting. Function signatures with appropriate variable names help explain the use to the user and are especially helpful when working in an IDE with autocomplete features. Limit arbitrary input (*args and **kwargs) to parameters that aren't necessary for typical use cases.
* Don't allow undefined behavior. Allowing requests to be made to GDAX with parameters that don't align to their specs invites undefined behavior from GDAX (if their response simply isn't an error) which is *the worst*. A minimal amount of checking in the Python API can catch these situations and display informative errors. A couple examples:
     * Required parameters. If the parameter is required by the API spec, it should be required by the Python function. Easy enough to do by not specifying default parameters for those variables.
    * Mutually exclusive parameters. For market orders, you specify either `size` or `funds` which correspond to an order in BTC or USD (for example). I don't want to find out what happens when you specify both parameters at once.

OK, that's it for now. Just trying to lay out the thought process behind the large changes that I'll be pushing soon. Happy to hear any input or additional thoughts.

**Comment by bryankaplan** [comment]
@acontry This all makes very good sense to me, and I'm happy to conform to these principles in my contributions. The two things that I'd add here are:
* We should establish a convention for error handling. See #27 for that discussion.
* It might be good to copy this writing to CONTRIBUTING.md

**Comment by danpaquin** [comment]
100% behind all of this. You all are bringing great ideas to the table.
