### ISSUE TITLE
get_product_historic_rates is fetching data outside the time frame for 60s granularity

### ISSUE THREAD

**Issue by tivvit** [danpaquin/coinbasepro-python#70]
Hi I have encountered a very strange behaviour.

I am almost sure that it is not the problem of the python GDAX library, but I want to be sure that it is not only my problem before I report it.

This is the code running with gdax installed from master

```python
import gdax
import datetime

product = "{}-{}".format("BTC", "EUR")
publicClient = gdax.PublicClient()
unit = 60
ten_min = datetime.timedelta(minutes=10)
now = datetime.datetime.now()
start = now - ten_min
print((now - start).seconds / unit)
print(now.isoformat())
print(start.isoformat())
hist = publicClient.get_product_historic_rates(
            product,
            start=start.isoformat(),
            end=now.isoformat(),
            granularity=unit)
print(datetime.datetime.fromtimestamp(int(hist[0][0])).isoformat())
print(datetime.datetime.fromtimestamp(int(hist[-1][0])).isoformat())
print(len(hist))
```
It should return 10 candles from last 10 minutes, but it returns 395 candles from several hours.
``` 
10.0
2017-06-19T19:40:51.551975
2017-06-19T19:30:51.551975
2017-06-19T19:39:00
2017-06-19T13:00:00
395
```
When I changed the granularity to 61 the output looks exactly as expected
```
9.836065573770492
2017-06-19T19:41:33.666923
2017-06-19T19:31:33.666923
2017-06-19T19:40:38
2017-06-19T19:31:29
10
```
Can anybody please confirm this behaviour?

**Comment by tivvit** [comment]
Hi, I thought about that and it is probably caching on the gdax side. It is not bug but it may cause some problems.

**Comment by bryankaplan** [comment]
I gave it a try, and with 60 received:
```
10.0
2017-06-20T06:17:35.001336
2017-06-20T06:07:35.001336
2017-06-19T23:17:00
2017-06-19T23:07:00
11
```
11 looks correct to me, because the range is inclusive.

Anyway, it might have been a gdax hiccup, or they might have a bug. If you see it again, you should probably open a ticket with them.

**Comment by tivvit** [comment]
It also works correctly for me now, so it definitely was a problem with gdax.
We may close this issue, but maybe we may add optional param which will throw away the data which you did not ask for. What do you think about that?

**Comment by danpaquin** [comment]
This is totally an issue with the exchange. I will leave this open for review from others passing by.  Any fixes around this should be handled locally as we would not expect this to be normal behavior.

Thank you for posting this!

**Comment by nickm4062** [comment]
I see similar behavior but I get 401 candles

**Comment by Algogator** [comment]
I'm getting

```
10.0
2017-07-18T14:36:46.499858
2017-07-18T14:26:46.499858
2017-07-18T14:36:00
2017-07-18T07:57:00
325
```

**Comment by nickjm** [comment]
I've also experienced this bug. Just happened a few minutes ago, as @tivvit described. Definitely seems to be a bug with gdax exchange.

**Comment by sumotide** [comment]
I was having a problem with GDAX returning what I was asking for too. I'm not a professional programmer and this is a little off topic, but I think there is a problem in the code above. Specifically, `now = datetime.datetime.now()`; it returns the ISO 8601 current  **_local_** date and time of the user. The problem is that GDAX API server time is not the same as the user current local time. 

For example, as I write this, `now = datetime.datetime.now() ` returns "2017-08-07 07:35:09.093873" which is correct because I live in California. However, the GDAX API server time is "2017-08-07T14:35:09.781Z". So it might help for accuracy sake to change `now = datetime.datetime.now()` to `datetime.datetime.now(pytz.timezone('GMT'))`.

Run the simple script below to find out how far off `datetime.datetime.now()`  is from the GDAX API server. 

```
import gdax
import time
import pytz
import datetime


for x in range(0,1000):
    print("This is local time:", datetime.datetime.now())
    print("Similar to GDAX API server: ", datetime.datetime.now(pytz.timezone('GMT')))
    print("This is GDAX API server time:", gdax.PublicClient().get_time(), "\n")
    time.sleep(15)
```

**Comment by bcbuckles** [comment]
I'm still seeing this issue. As mentioned above, changing granularity=61 returns the results expected for granularity=60. Any updates on this bug? This makes it hard to make a robust function for retrieving data since the results are unreliable.

**Comment by sumotide** [comment]
It's a bug with GDAX, not the library. I built a separate script to obtain results and put into DB table every 400 minutes (checking for duplicates and update accordingly). Another script pulls data from DB AND polls data from GDAX (using 61s granularity) to keep data up to date while graphing is open.

**Comment by r-kalma** [comment]
Did anyone actually manage to pull 1min data from GDAX using this library? I'm having trouble getting this to work. Even with using the 61s granularity workaround, I'm not getting the expected results:

```
gg = pd.DataFrame(gd_public.get_product_historic_rates('ETH-BTC', start = 1508490000, granularity=61))
print(gg.head(1))
print(gg.tail(1))

gg = pd.DataFrame(gd_public.get_product_historic_rates('ETH-BTC', start = 1508454000, granularity=61))
print(gg.head(1))
print(gg.tail(1)) 
```

   0        1        2        3        4          5
0  1508576665  0.04888  0.04888  0.04888  0.04888  14.181419
             0        1        2        3        4          5
26  1508573127  0.04895  0.04913  0.04895  0.04913  24.954434
            0        1        2        3        4          5
0  1508576665  0.04888  0.04888  0.04888  0.04888  14.181419
             0        1        2        3        4          5
26  1508573127  0.04895  0.04913  0.04895  0.04913  24.664434

**Comment by impshum** [comment]
I'm getting 372 for 60. Such problems!

**Comment by danpaquin** [comment]
Since this is such a persistent issue, I am considering handling the erroneous responses as part of the package.  Previously, we discussed how this wrapper should be as minimal as possible, but it doesn't hurt to double check we're returning data as expected.

**Comment by diyahir** [comment]
I'm not sure if this has been resolved, but I found the jerry-rigged fix. Simply add 6 hours to and from the actual desired time when calling the get_product_historic_rates() method. Keep in mind that I am in central time, not sure if it matters. This should be updated in the wrapper.
